### ISSUE TITLE
Is there any implementation of the Exact initial Kalman Filter?

### ISSUE THREAD

**Issue by EulerFaria** [rlabbe/filterpy#145]
First, congratulations for this awesome library and book! Great job!! 

This is just a question, in your library is there any implementation of the Exact initial Kalman Filter described on chapter 5 of Durbin and Koopman book (Time-Analysis-State-Space-Methods) ?  If not do you know any library with this implementation in Python ? I have looked at Statsmodels, but they don't have it yet. 

Thank you in advance.

**Comment by rlabbe** [comment]
No, there isn't. I'm not necessarily adverse to implementing it, but haven't ever used it before. in general my library is meant more for learning about filters than trying to implement the universe of various state space methods.

The Information Filter also allows you to start a filter with unknown initial conditions. However, I warn you that I am tracking down a bug in that code at the moment, and I would not use the class (InformationFilter) until that bug is fixed. This is referenced in #143.

**Comment by rlabbe** [comment]
I'm going to close this; I have no plans to comprehensively implement all possible Bayesian filters.
