### ISSUE TITLE
Move matplotlib to extras_require dict within setup.py

### ISSUE THREAD

**Issue by jfinken** [rlabbe/filterpy#163]
_Many_ thanks for moving the matplotlib imports within the various functions of `stats.py` that use matplotlib.

Please then consider moving `matplotlib` to the `extras_require` dict of setup.py.  For example:

```
setup(
    name='filterpy',
    ...
    extras_require = {"stats": ["matplotlib"]}
    ...
)
```
This allows us, for which matplotlib causes issues, to still install the wonderful `filterpy` (without having to uninstall matplotlib after the fact).  Folks can still install `filterpy` with `matplotlib` via:

    pip install filterpy[stats]

Thoughts?

Thanks!

**Comment by rlabbe** [comment]
I'll have to read about that. I'm not super excited about having to use pip install filterpy[stats] since stats isn't exactly optional, and the vast number of people want to use plotting.

I think the answer is to leave matplotlib out of the install_requires variable, and then make multiple requirements.txt files, one that includes matplotlib, one not. I don't know. That may not work for environments like binder, which use the install_requires to automatically make a container for your project.

In the end I want to support your request, but not at the cost of reduced functionality for everyone else. I'm open to suggestions; I'm no setuptools guru.

**Comment by rlabbe** [comment]
Actually, can't you just use pip install filterpy --no-dep?  and then install NumPy/SciPy if needed?

**Comment by jfinken** [comment]
Hi Roger, 
Many thanks for the swift reply!  I certainly acknowledge that the number of users who `pip install filterpy` and who then want and expect matplotlib will vastly outnumber, well, me.    So I'll see if there is a workaround on my end.

`pip install filterpy --no-dep` doesn't quite work as I am specifying `filterpy` within the setup.py and requirements.txt of yet another library package.  (akin to `filterpy[no-dep]==1.4.4` in my setup.py would be ideal for example).

I do see many methods within your `stats` subpackage are not optional but the `plot_*` methods do appear to be optional.  Thus in principle, I am forced to install matplotlib but at best do not require it.

Again many thanks for the reply.
Regards,
-Josh
