### ISSUE TITLE
Incorrect prior update in EnKF

### ISSUE THREAD

**Issue by kai1337** [rlabbe/filterpy#165]
Dear all,

in file filterpy/filterpy/kalman/ensemble_kalman_filter.py in the predict() method I noticed that only the ensemble members (self.sigmas) are updated by function self.fx(...). However, the mean state self.x is not updated in this method even if it is used to save the next self.x_prior (line 300). Furthermore, this also influences the whole result of the filter since self.x is used in the update method (line 265). If I'm not mistaken, one should add the line 
self.x = np.mean(self.sigmas, axis=0)
shortly before line 300.

**Comment by rlabbe** [comment]
Opps! fixed.

**Comment by kai1337** [comment]
Sorry to bother you again, but I just noticed that self.x is used in line 294 as well. Don't you need to update self.x before that line?

**Comment by rlabbe** [comment]
You are, of course, correct. I'm not very happy with this class at the moment. It obviously was not debugged/tested very well, and it is woefully inefficient in its computations using loops instead of vectorizations. I'm going to do a code review and refactor of this class, and open an issue for that action.
