### ISSUE TITLE
Confidence interval calculation help for kalman filter

### ISSUE THREAD

**Issue by jaideeplamba** [rlabbe/filterpy#183]
First of thank you for all the fabulous work with library and book.

I am trying to understand/compare difference between Kalman filter local level model vs ZeroOrder filterpy model. Confidence interval in two scenarios is very different. Pointers to resolve this difference is greatly appreciated.

Local Level Model as implemented in KFAS library in R and documented here https://radhakrishna.typepad.com/TimeSeries_Analysis_State_Space_Methods.pdf. It uses Nile data and code that I used is on page 6. You dont need to run the code but notice the confidence interval band in fig 2.1)i

Now compare that against zeroOrderModel in filterpy. Confidence interval band coming from filterpy is very narrow. I am fairly sure that I am doing something wrong so will appreciate some help. Code below to illustrate my calculations for confidence interval.

def ZeroOrderKF(R, Q, P=20):
    """ Create zero order Kalman filter.
    Specify R and Q as floats."""
    
    kf = KalmanFilter(dim_x=1, dim_z=1)
    kf.x = np.array([0.])
    kf.R *= R
    kf.Q *= Q
    kf.P *= P
    kf.F = np.eye(1)
    kf.H = np.eye(1)
    return kf    

ts = nile["Actual"]
R, Q = 1, 0.001
kf = ZeroOrderKF(R, Q)
zs = np.array(ts) 
data1 = filter_data(kf, zs)

results = np.asarray(data1.x[:,0])
var = np.asarray(data1.P[:,0])
std = np.sqrt(var)
std_top_v2 = results+(1.64*std[:,0])
std_btm_v2 = results-(1.64*std[:,0]) 

Regards,
Jaideep

![image](https://user-images.githubusercontent.com/4401688/57174764-2b327980-6e09-11e9-82ad-d546a13c0b5b.png)

![image](https://user-images.githubusercontent.com/4401688/57174768-4a310b80-6e09-11e9-9358-e6876187282f.png)

**Comment by rlabbe** [comment]
I can't really read publications and then debug code on private projects. Plus, your example is incomplete; filter_data is undefined, and I don't know how these plots were generated. 

I'm going to close this because no one has chimed in for a year. All I can say is I have no idea what BFGS means, or what Q and R is in the R code (I don't need the answer, I'm not looking further), nor what process model the R code is using. I'd start by looking at that.
