### ISSUE TITLE
How can I use KalmanFilter to forecast x periods out ?

### ISSUE THREAD

**Issue by jaideeplamba** [rlabbe/filterpy#184]
How can I use Kalman filter to predict x periods out along with its associated confidence interval band ?
Thanks.

**Comment by DerekGloudemans** [comment]
I believe you need to do the predict step several times, predicting the state estimate and state error covariance estimate without carrying out the update step (because no new measurements are observed). The state error covariance should increase with each prediction step. For each state variable (nominally x[i]), the associated variance will be found along the main diagonal in the ith position of the covariance matrix (nominally P[i,i]).

**Comment by rlabbe** [comment]
Yes, you can either call predict repeatedly if measurements are otherwise periodic, or just recompute F and Q for the period you want to predict for and call predict once.
