### ISSUE TITLE
Numba

### ISSUE THREAD

**Issue by sede10** [rlabbe/filterpy#227]
Hello, it would be good to see Numba support in this library. Given "impressive speedups" it should be available, at least as an option. Processing large amounts of data can get slow compared to calculating something like moving average.

**Comment by rlabbe** [comment]
Not so easy to do.

1. People complain about the dependencies already. Matplotlib being the main one. I don't want to pull numba in if I don't need to. Sure, I could make separate modules for numba support, such as `import filterpy.jittedkalmanfilter` or something, but I'm honestly not going to maintain two nearly identical code bases.
2. Okay, you can remove the dependency with a try/except block. If the numba import fails, define my own jit operator that does nothing. I fought that for awhile and gave up, but it should be doable.

3. In general I have had trouble getting any real speed up, though I just tried it again and did get a 4x speed up on the standalone update() function. Great! Maybe things have improved, or I just used numba better this time. But now see point 4

4. I couldn't get update to jit without heavy modification. For example, ` Hx = np.atleast_1d(dot(H, x))` won't compile because numba can't deal with different types. My functions are pretty flexible - x can be a scalar, 1d array, or 2d array and the code works. I had to remove that flexibility - no try/except, no working with different format inputs. To be honest I fairly regret this flexibility as it leads to a lot of questions and misuse (kf appears to run, but because of badly formatted input it isn't doing what the author thinks it does). But I also hated that Python 3 broke so much code - do I want to do that to people? Not so much. So I'll probably let it stay. 

5. There is really poor support for classes in numba, though it appears to be improving. The docs currently state "This is a early version of jitclass support. Not all compiling features are exposed or implemented, yet." Last time I tried I couldn't get it to work with any of my classes.

6. This is a pedagogical library. My sincere hope is that people read the code, and not just 'use it'. I recognize people have work to get done, and have little interest in the machinery. But I'm supporting students. That's all I care about. So the idea of modifying a bunch of code to support numba, and only be able to take pull requests that works with numba isn't appealing to me.

7. But hey, open source! If somebody thinks they can achieve/work-around all my concerns above, I'd love a pull request.

**Comment by jampekka** [comment]
For those interested, the Kalman filter's procedural API is quite straightforward to turn into a numba-compatible format. What causes problems are the typecastings from scalars and the full return of `update`, but pruning those out leads to njittable functions. A batch version using these should be simple to implement.

Given the API's flexibility, porting the functions as-is to numba may be difficult.

```python
from numba import njit
from numpy import dot, linalg
import numpy as np

@njit
def update(x, P, z, R, H):
    Hx = dot(H, x)

    # error (residual) between measurement and prediction
    y = z - Hx

    # project system uncertainty into measurement space
    S = dot(dot(H, P), H.T) + R

    # map system uncertainty into kalman gain
    K = dot(dot(P, H.T), linalg.inv(S))

    # predict new x with residual scaled by the kalman gain
    x = x + dot(K, y)

    # P = (I-KH)P(I-KH)' + KRK'
    KH = dot(K, H)

    I_KH = np.eye(KH.shape[0]) - KH
    P = dot(dot(I_KH, P), I_KH.T) + dot(dot(K, R), K.T)

    return x, P

@njit
def predict(x, P, F, Q=0, alpha=1.):
    x = dot(F, x)
    P = (alpha * alpha) * dot(dot(F, P), F.T) + Q

    return x, P
```

**Comment by rlabbe** [comment]
I just tried, your code does run faster, but I still stand behind my comments. People *hate* dependencies. And really, a KF is just a few lines of code; if speed is everything to you grab the code above and you'll be fine. 

I'm still resisting adding it because it will become a maintenance nightmare. In practice, when I am using KF at work I care about all the intermediate calculations - S, K, etc. 'Losing' those in stand alone functions is a non-starter. So you'd have to return all of them. And then people are going to ask for all the other functions to be included - RTS, correlated, etc. It'll essentially become two libraries in one. I guess I'd have to write all of the code as stand alone functions, and then call them from my classes, storing the output in self.blah. It doesn't quite appeal to me when I am not keeping up with the regular issues and pull requests. 

I'm going to close this - people can still comment, or even proffer a pull request. I discourage the latter without discussing it with me first, as I'm almost certain to say no unless it is truly transparent to the end user. This is being used in school and industry; I don't want some student trying to get their homework done fighting with numba. That serves no one. If you care about speed, copy @jampekka 's useful code.
