### ISSUE TITLE
Using UKF for sensor fusion

### ISSUE THREAD

**Issue by cmasseraf** [rlabbe/filterpy#30]
Hi,

I'd like to use filterpy's UKF for sensor fusion. However I have two different measurement sources with different sizes, how can I setup the filter to make this work?

Thanks,
Carlos

**Comment by rlabbe** [comment]
Hi, I'm sorry, but I don't fully understand your question. What does "different sizes" mean? 

My book goes through various sensor fusion scenarios, if you haven't read it it is here:
https://github.com/rlabbe/Kalman-and-Bayesian-Filters-in-Python

**Comment by MRoobeek89** [comment]
I think my question is on the same topic, maybe this is helpful for @cmasseraf as well:

The observation function currently only allows the state as an input: y = h(x(t)).
How do I feed sensor measurements (that are clearly not part of the state vector) into the function?
y(t) = h( x(t), **u(t)** )

For example, I would like to define the observation function as follows:
```
def observation_function(x, u):
    x1 = u[0] 
    x2 = u[1] 
    return np.array([x1, x2])
```

Thanks in advance!

**Comment by rlabbe** [comment]
All this function is supposed to do is convert the current state (the prior) into the equivalent measurement - it does not incorporate the measurements in any way.  If you fed the measurements in here, then when the filter computes the residual the residual will always be zero. Am I misunderstanding your question?

**Comment by MRoobeek89** [comment]
Thanks for the quick reply, I think I misunderstood the goal of the function.

**Comment by rlabbe** [comment]
my kalman filter book goes into it in depth, if you haven't read it. If you have, maybe I need to revisit that chapter to better clarify this?

**Comment by randvoorhies** [comment]
Sorry to comment on a closed issue, but I'd like to chime in and say it's really not clear from the docs how to call `UnscentedKalmanFilter.update()` using multiple sensors.  Let me give an illustrative example:

I am running a UKF on my robot and have the following state vector: `<x, y, θ, v, ω>`, where `<x, y, θ>` is the robot's pose in a global frame and `<v, ω>` is the linear/angular velocity in the robot's frame.  My robot is equipped with a GPS which can observe `<x, y>`, as well as wheel encoders which observe `<v, ω>`, a compass which observes just `<θ>`, and a gyroscope which observes just `<ω>`.  To make things even more fun, all of my sensors report in at different rates.

Unless I'm missing something, the UnscentedKalmanFilter constructor requires the user to specify a single `dim_z` parameter, so I'm not sure how to use it in a multi-sensor setup.  It would be excellent if `dim_z`, `hx`, `z_mean_fn`, and `residual_z` could all be passed into `update()` rather than provided up front.
