### ISSUE TITLE
UKF Different Updates

### ISSUE THREAD

**Issue by geoffviola** [rlabbe/filterpy#61]
Is there an example of a filter taking in different measurements at different times? Does the library support this feature? It seems that the UKF in particular does not support this. It would improve the usefulness of the library.

**Comment by rlabbe** [comment]
My book has several examples: https://github.com/rlabbe/Kalman-and-Bayesian-Filters-in-Python

In general, though, there is no problem in doing this. Any matrix/function that includes \delta t needs to be recomputed before the update/predict cycles so the computations are correct, but otherwise everything proceeds apace. For example, the state transition matrix F contains \delta t for motion models. If measurements come in at time t=0.1, 0.2, 0.3, 0.5, then \delta t = 0.1 for the first 2 predict calls, and then \delta t = 0.2 for the third (to account for gap between 0.3 to 0.5.

If you mean *out of sequence* measurements, e.g. t = 3, t = 5, t = 4, then no. There is theory to account for this, but I have not studied it, and thus not implemented it. This library was created for pedagogical reasons, so there are some real limits to the library.

**Comment by geoffviola** [comment]
Thanks. That's good information.

In your robot example, you have some landmarks coming. What if you receive the landmark measurements at 1 Hz and some other type of measurement at a different rate. For example, what if you also received velocity and turn rate at 10Hz.

**Comment by geoffviola** [comment]
I couldn't figure out how to make the UKF implementation work. Instead, I rewrote the EKF implementation. EKF's make more sense to me right now even though the book recommends UKF's in general.

Chapter 6 has some simple examples for updates that don't observe the entire state space. Basically, anytime the size of matrix H does not equal the size of matrix P.

**Comment by rlabbe** [comment]
This is really old, I'm going to close it. In general you can call update however and whenever you like. If the measurements are of a different type per update, then you have to modify H prior to the call. If things get too complicated, perhaps it is better to just write the KF explicitly; there is a limit to how flexible you can make a class and have it still easily usable. I think the UKF is a good example of pressing those limits - it has a lot of 'moving parts' because of the flexibility I built into it, and it is thus non-trivial to get a working example going.

As always, reopen or create a new PR if there are remaining questions.
